export { default as song1 } from './song1'
export { default as song2 } from './song2'
export { default as song3 } from './song3'
export { default as pickup } from './pickup'
export { default as damage } from './damage'